swagger: '2.0'
info:
  version: 1.0.0
  title: "API Locación"
basePath: "/c3p"
schemes:
  - https
paths:
  "/v1/Portal/Locacion":
    post:
      tags:
      - "Locacion"
      operationId: postLocacion
      summary: Crea una Locacion
      description: Crea un Locacion
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-RqUID
          description: Identificador único del mensaje.
          in: header
          required: true
          type: string
          maxLength: 36
          minLength: 1
        - name: ReqPostLocacion
          in: body
          required: true
          schema:
            $ref: '#/definitions/ReqPostLocacion'
      responses:
        '201':
          description: creado
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
        '206':
          description: Error en la transacción
          schema:
            $ref: '#/definitions/Error'
          headers:
            X-RqUID:
              type: string
              description:  Identificador único del mensaje.
  "/v1/Portal/Locacion/{Codigo}":
    get:
      tags:
      - "Locacion"
      operationId: getLocacion
      summary: Consultar una Locacion
      description: Consultar una Locacion
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-RqUID
          description: Identificador único del mensaje.
          in: header
          required: true
          type: string
          maxLength: 36
          minLength: 1
        - name: Codigo
          description: Identificador único del mensaje.
          in: path
          required: true
          type: string
      responses:
        '200':
          description: exitoso
          schema:
            $ref: '#/definitions/RespGetLocacion'
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
        '206':
          description: Error en la transacción
          schema:
            $ref: '#/definitions/Error'
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
  "/v1/Portal/Locaciones":
    get:
      tags:
      - "Locacion"
      summary: Consultar lista de Locaciones
      description: Consultar lista de Locaciones
      operationId: getLocaciones
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-RqUID
          description: Identificador único del mensaje.
          in: header
          required: true
          type: string
          maxLength: 36
          minLength: 1
      responses:
        '200':
          description: exitoso
          schema:
             type: "array"
             items:
              $ref: "#/definitions/RespGetLocacion"
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
        '206':
          description: Error en la transacción
          schema:
            $ref: '#/definitions/Error'
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
definitions:
  ReqPostLocacion:
    type: object
    properties:
      Codigo:
        type: string
      Nombre:
        type: string
      Direccion:
        type: string
      Barrio:
        type: string
      Sector:
        type: string
      Representante:
        type: string
      Correo:
        type: string
      Telefono:
        type: string
  RespGetLocacion:
    type: object
    properties:
      Codigo:
        type: string
      Nombre:
        type: string
      Direccion:
        type: string
      Barrio:
        type: string
      Sector:
        type: string
      Representante:
        type: string
      Correo:
        type: string
      Telefono:
        type: string
  Error:
    type: object
    properties:
      Codigo:
        type: string
      Mensaje:
        type: string
